[project]
name = "echomind"
version = "0.1.0"
description = "EchoMind â€” An Agentic Short-Term Memory System for LLMs "
requires-python = ">=3.10, <3.13"
dependencies = [
    "agentuity>=0.0.106",
    "openai>=2.7.1",
]
